services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.docker
    volumes:
      - pg:/var/lib/postgresql/data
  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env.docker

volumes:
  pg: # volume para os postgres